try:
    print(x)
except:
    print("Algo salio mal")
finally:
    print("termino el bloque de 'try except'")